# Generated by Django 4.0 on 2023-12-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('thana', models.CharField(max_length=50, verbose_name='Thana')),
                ('zilla', models.CharField(max_length=50, verbose_name='zilla')),
                ('description_title', models.CharField(max_length=50, verbose_name='Desciption Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('student_count', models.IntegerField(verbose_name='Student Count')),
                ('teacher_count', models.IntegerField(verbose_name='Teacher Count')),
                ('class_count', models.IntegerField(verbose_name='Class Count')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('designation', models.CharField(max_length=50, verbose_name='Designation')),
                ('fb_link', models.CharField(blank=True, default='#', max_length=255, null=True, verbose_name='Facebook')),
                ('linkedIn_link', models.CharField(blank=True, default='#', max_length=255, null=True, verbose_name='LinkedIn')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
                ('picture_url', models.ImageField(blank=True, null=True, upload_to='upload_image/')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
    ]
