# Generated by Django 4.0 on 2023-12-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[('Headmaster', 1), ('Asstistant Headmaster', 2), ('Teacher', 3)], default='Teacher', max_length=255),
        ),
    ]
