# Generated by Django 4.0 on 2023-12-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_teacher_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(default='Teacher', max_length=255),
        ),
    ]
