# Generated by Django 4.0 on 2023-12-18 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notice_alter_teacher_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 18, 14, 32, 52, 563306)),
        ),
    ]
