# Generated by Django 4.0 on 2023-12-19 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notice_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 19, 17, 2, 10, 580614)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(default='Asst. Teacher', max_length=255),
        ),
    ]
