# Generated by Django 4.0 on 2023-12-19 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_notice_publish_date_alter_teacher_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='picture_url',
            new_name='picture',
        ),
        migrations.AlterField(
            model_name='notice',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 19, 17, 4, 13, 515267)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(default='Asstistant Teacher', max_length=255),
        ),
    ]
