# Generated by Django 4.0 on 2023-12-21 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_picture_url_teacher_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('file', models.FileField(blank=True, null=True, upload_to='ClassRoutine/%Y/%m/%d', verbose_name='File')),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 21, 14, 29, 48, 865366))),
            ],
            options={
                'verbose_name': 'Class Routine',
                'verbose_name_plural': 'Class Routines',
            },
        ),
        migrations.AlterField(
            model_name='notice',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 21, 14, 29, 48, 864362)),
        ),
    ]
