# Generated by Django 4.0 on 2023-12-22 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_classroutine_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroutine',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 22, 16, 12, 47, 119072)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 22, 16, 12, 47, 118074)),
        ),
    ]
