# Generated by Django 4.0 on 2024-01-19 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_teacher_email_alter_classroutine_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroutine',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 19, 15, 58, 29, 466867)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 19, 15, 58, 29, 466867)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[('HEAD_OF_INSTITUTION', 'Headmaster'), ('VICE_HEAD_OF_INSTITUTION', 'Assistant Headmaster'), ('TEACHER', 'Asstistant Teacher'), ('INSTRUCTOR', 'Instuctor')], default='Asstistant Teacher', max_length=255),
        ),
    ]
