# Generated by Django 4.0 on 2024-01-19 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_classroutine_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroutine',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 19, 16, 4, 8, 85431)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 19, 16, 4, 8, 85431)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[('Headmaster', 'Headmaster'), ('Assistant Headmaster', 'Assistant Headmaster'), ('Asstistant Teacher', 'Asstistant Teacher'), ('Instuctor', 'Instuctor')], default='Asstistant Teacher', max_length=255),
        ),
    ]
