# Generated by Django 4.0 on 2024-01-19 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_classroutine_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroutine',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 19, 16, 13, 41, 525540)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.FileField(default=1, upload_to='notices/%Y/%m/%d', verbose_name='File'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notice',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 19, 16, 13, 41, 525540)),
        ),
    ]
