# Generated by Django 4.0 on 2024-01-19 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_classroutine_publish_date_alter_notice_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='headmaster_speech',
            field=models.TextField(blank=True, null=True, verbose_name='Headmaster Speech'),
        ),
        migrations.AlterField(
            model_name='classroutine',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 19, 16, 45, 22, 18015)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 19, 16, 45, 22, 18015)),
        ),
    ]
