# Generated by Django 4.0 on 2025-08-05 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_classroutine_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroutine',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 5, 9, 44, 51, 537688)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 5, 9, 44, 51, 537688)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[('Headmaster', 'Headmaster'), ('Assistant Headmaster', 'Assistant Headmaster'), ('Assistant Teacher', 'Assistant Teacher'), ('Instructor', 'Instructor'), ('Lab Assistant', 'Lab Assistant'), ('Office Assistant / Computer Operator', 'Office Assistant / Computer Operator'), ('Demonstrator', 'Demonstrator')], default='Assistant Teacher', max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
