# Generated by Django 4.0 on 2025-08-05 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_classroutine_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroutine',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 5, 11, 27, 7, 326942)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 5, 11, 27, 7, 325943)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='fb_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='linkedIn_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LinkedIn'),
        ),
    ]
