# Generated by Django 4.0 on 2025-08-05 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_classroutine_publish_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('designation', models.CharField(choices=[('office_assistant', 'Office Assistant'), ('cleaner', 'Cleaner'), ('security_guard', 'Security Guard'), ('AYA', 'AYA'), ('night_guard', 'Night Guard'), ('shop_assistant', 'Shop Assistant')], max_length=20, verbose_name='Designation')),
                ('fb_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook Profile URL')),
                ('linkedIn_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='LinkedIn Profile URL')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='stuff/profile_pics/', verbose_name='Profile Picture')),
            ],
            options={
                'verbose_name': 'Stuff',
                'verbose_name_plural': 'Stuffs',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='classroutine',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 5, 12, 10, 46, 298762)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 5, 12, 10, 46, 298762)),
        ),
    ]
