# Generated by Django 5.2.4 on 2025-08-05 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_stuff_alter_classroutine_publish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='History'),
        ),
        migrations.AlterField(
            model_name='classroutine',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 5, 21, 53, 50, 716880)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 5, 21, 53, 50, 716880)),
        ),
    ]
